import { createHash } from 'node:crypto';

// Facts generated by tmt2-data; handwritten consumers never infer callbacks.
export interface SeedCatalog {
	metadata: {
		generator: string, version: string, datasetHash: string, catalogHash: string, baseServerCommit: string,
		formatID: string, formatName: string, modID: string,
	};
	seed: {
		teams: { id: string, sets: PokemonSet[] }[],
		forms?: {
			id: string, name: string, baseSpecies: string, forme: 'Mega', requiredItem: string,
			types: string[], baseStats: StatsTable, abilities: string[], learnset: string[],
		}[],
		species: {
			id: string, name: string, types: string[], baseStats: StatsTable, abilities: string[], learnset: string[],
		}[],
		moves: { id: string }[],
		abilities: { id: string, name: string }[],
		items: { id: string }[],
		types: { id: string, name: string }[],
	};
	table: { types: { [id: string]: { damageTaken: { [name: string]: number } } } };
}
export const Catalog: SeedCatalog = require('./catalog.json');
if (Catalog.metadata.generator !== 'tmt2-data/tmt05-v1' || Catalog.metadata.modID !== 'gen9tmt2seed') {
	throw new Error('Missing or incompatible TMT2 catalog; regenerate from validated tmt2-data');
}

function canonical(value: unknown): unknown {
	if (Array.isArray(value)) return value.map(canonical);
	if (value && typeof value === 'object') {
		const object = value as { [key: string]: unknown };
		return Object.fromEntries(Object.keys(object).sort().map(key => [key, canonical(object[key])]));
	}
	return value;
}
const factsHash = createHash('sha256')
	.update(JSON.stringify(canonical({ seed: Catalog.seed, table: Catalog.table }))).digest('hex');
const datasetHash = createHash('sha256').update(JSON.stringify(canonical(Catalog.seed))).digest('hex');
if (Catalog.metadata.catalogHash !== factsHash || Catalog.metadata.datasetHash !== datasetHash) {
	throw new Error('TMT2 generated catalog drift; regenerate compatible data');
}
